server:
  port: 8081
    
spring:
  application:
    name: fast-platform-spring
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    postgresql:
      jdbc-url: jdbc:postgresql://localhost:5432/fast_platform?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true&rewriteBatchedStatements=true&currentSchema=fp
      username: postgres
      password: postgrespwd
      driver-class-name: org.postgresql.Driver
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        idle-timeout: 300000
        connection-timeout: 20000
        max-lifetime: 1200000
    mysql: # 备用MySQL配置
      jdbc-url: jdbc:mysql://localhost:3306/fast_platform?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true&rewriteBatchedStatements=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        idle-timeout: 300000
        connection-timeout: 20000
        max-lifetime: 1200000
  jpa:
    properties:
      hibernate:
        '[show_sql]': true
        '[format_sql]': true
        jdbc:
          lob:
            '[non_contextual_creation]': true
    hibernate:
      ddl-auto: update


############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token: 
    # token 名称（同时也是 cookie 名称）
    token-name: satoken
    # token 有效期（单位：秒） 默认30天，-1 代表永久有效
    timeout: 2592000
    # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
    active-timeout: -1
    # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
    is-concurrent: true
    # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
    is-share: true
    # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
    token-style: uuid
    # 是否输出操作日志 
    is-log: true

logging:
  level:
    org.springframework.boot.autoconfigure.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG
    org.hibernate.dialect: TRACE